'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MYTYPE = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MYTYPE = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public ReadOnly Property LAReady() As Boolean
            Get
                Return CType(Me("LAReady"), Boolean)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.10.218.101:8080/services/codeMappingService")>
        Public ReadOnly Property CS2005_DMSWS_CodeMappingServiceImplService() As String
            Get
                Return CType(Me("CS2005_DMSWS_CodeMappingServiceImplService"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("max pool size=500;server=HKSQLUAT1;database=INGCIWU301;Network=DBMSSOCN;uid=com_l" &
            "as_ing;password=XXXXX")>
        Public ReadOnly Property strCIWConn() As String
            Get
                Return CType(Me("strCIWConn"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("max pool size=500;server=HKSQLUAT1;database=INGPROFILEU301;Network=DBMSSOCN;uid=c" &
            "om_las_ing;password=XXXXX")>
        Public ReadOnly Property strUPSConn() As String
            Get
                Return CType(Me("strUPSConn"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("server=HKSQLUAT1;database=MPFAETNA;Network=DBMSSOCN;uid=com_las_ing;password=XXXX" &
            "X")>
        Public ReadOnly Property strMPFConn() As String
            Get
                Return CType(Me("strMPFConn"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("max pool size=500;server=HKSQLUAT1;database=INGMCSU301;Network=DBMSSOCN;uid=com_l" &
            "as_ing;password=XXXXX")>
        Public ReadOnly Property strMCSConn() As String
            Get
                Return CType(Me("strMCSConn"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("max pool size=500;server=HKSQLUAT1;database=INGMCSU301;Network=DBMSSOCN;uid=com_l" &
            "as_ing;password=XXXXX")>
        Public ReadOnly Property strMJCConn() As String
            Get
                Return CType(Me("strMJCConn"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.10.218.125:11020/#/login?lang=eng")>
        Public ReadOnly Property CS2005_CoBrowsUrl() As String
            Get
                Return CType(Me("CS2005_CoBrowsUrl"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("https://uat-eservices.hk.intranet/aa/fwd/landing/cer/")>
        Public ReadOnly Property CS2005_AAUrl() As String
            Get
                Return CType(Me("CS2005_AAUrl"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/CRSWS/CRSWS.asmx")>
        Public ReadOnly Property CS2005_CRSWS_CRSWS() As String
            Get
                Return CType(Me("CS2005_CRSWS_CRSWS"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/ClaimWS/MCSWS.asmx")>
        Public ReadOnly Property CS2005_MCSWS_MCSWS() As String
            Get
                Return CType(Me("CS2005_MCSWS_MCSWS"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/LEVYWS/LevyWS.asmx")>
        Public ReadOnly Property CS2005_LEVYWS_LEVYWS() As String
            Get
                Return CType(Me("CS2005_LEVYWS_LEVYWS"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/CCRWS/Service.asmx")>
        Public ReadOnly Property CS2005_CCRWS_Service() As String
            Get
                Return CType(Me("CS2005_CCRWS_Service"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/CNBWS/NBWrapper.asmx")>
        Public ReadOnly Property CS2005_CNBWrapper_NBWrapper() As String
            Get
                Return CType(Me("CS2005_CNBWrapper_NBWrapper"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/NBAWS/NBAWS.asmx")>
        Public ReadOnly Property CS2005_NBAWS_NBAWS() As String
            Get
                Return CType(Me("CS2005_NBAWS_NBAWS"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/commonws/service.asmx")>
        Public ReadOnly Property CS2005_CommonWS_Service() As String
            Get
                Return CType(Me("CS2005_CommonWS_Service"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://hkgcomprj02.hk.intranet:8013/POSWS/POSWS.asmx")>
        Public ReadOnly Property CS2005_POSWS_POSWS() As String
            Get
                Return CType(Me("CS2005_POSWS_POSWS"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("https://uat-eservices.fwd.com.hk/MCaa4/fwd/landing/cer/")>
        Public ReadOnly Property CS2005_AAUrl_MC() As String
            Get
                Return CType(Me("CS2005_AAUrl_MC"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("kenny.siu@fwd.com")>
        Public ReadOnly Property CS2005_SPAdd() As String
            Get
                Return CType(Me("CS2005_SPAdd"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("kenny.siu@fwd.com;alex.th.lee@fwd.com")>
        Public ReadOnly Property CS2005_SPCCAdd() As String
            Get
                Return CType(Me("CS2005_SPCCAdd"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://whkeaslasappu02/INGU102CCMWS/CCMWS.asmx")>
        Public ReadOnly Property CS2005_CCMWS_CCMWS() As String
            Get
                Return CType(Me("CS2005_CCMWS_CCMWS"), String)
            End Get
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.CS2005.My.MySettings
            Get
                Return Global.CS2005.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
